dist: bionic
services:
  - docker
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git clone https://${TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
# before_script:
# script:
#   - git submodule update --init --recursive
#   - bin/git-update.sh
#   - docker-compose up -d
#   - sleep 180
#   - docker ps --format '{{.Image}}' | sort >> docker_up_output.txt
#   - DIFF=$(diff docker_up_output.txt image_names.txt) 
#   - if [ "$DIFF" != "" ] ;  then
#        exit 1
#     fi