dist: bionic
services:
  fetch:
    volumes:
      - "./fetch:/app"
    depends_on:
      - fetch-background
    build: fetch
    ports:
      - "9292:9292"
    env_file:
      - fetch/.env_file
    command: start_server
  fetch-background:
    volumes:
      - "./fetch:/app"
    depends_on:
      - elasticsearch
      - kibana
      - redis
    build: fetch
    env_file:
      - fetch/.env_file
    command: wait_for_es_and_start_server 
git:
  submodules: false
before_install:
  - git clone https://${TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
before_script:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - cd fetch 
  - git checkout test/8830-automated-test
  - cd - 
script:
  - docker-compose build
  - docker-compose up --abort-on-container-exit
  # - ./bin/first-build.sh
  - docker ps --format '{{.Image}}' | sort
  # - docker ps --format '{{.Image}}' | sort >> docker_up_output.txt
  # - cat docker_up_output.txt
  # - cat image_names.txt
  # - DIFF=$(diff docker_up_output.txt image_names.txt) 
  # - if [ "${DIFF}" != "" ];  then
  #     exit 1;
  #   fi;