dist: bionic
git:
  submodules: false
before_install:
  - git clone https://${TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
before_script:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sed -i 's/--abort-on-container-exit/-d/' bin/first-build.sh
  - cd fetch 
  - git checkout develop
  - TAB=$'\t'
  - sed -i '/-c 5/ a \'"${TAB}"'\ until curl --silent -XGET --fail http://elasticsearch:9200; do printf \'.'\; sleep 1; done' Makefile
  - cd - 
script:
  - ./bin/first-build.sh
  - docker ps --format '{{.Image}}' | sort
  # - docker ps --format '{{.Image}}' | sort >> docker_up_output.txt
  # - cat docker_up_output.txt
  # - cat image_names.txt
  # - DIFF=$(diff docker_up_output.txt image_names.txt) 
  # - if [ "${DIFF}" != "" ];  then
  #     exit 1;
  #   fi;