dist: bionic
services:
  - docker
before_install:
  - git clone https://${TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
  - echo "pw1"
  - pwd
before_script:
  - echo "pw2"
  - pwd
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
script:
  - echo "pw3"
  - pwd
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - cat .gitmodules
  - bin/git-update.sh
  - docker-compose up -d
  - sleep 180
  - docker ps --format '{{.Image}}' | sort
# - docker ps --format '{{.Image}}' | sort >> docker_up_output.txt
#   - DIFF=$(diff docker_up_output.txt image_names.txt) 
#   - if [ "$DIFF" != "" ] ;  then
#        exit 1
#     fi