dist: bionic
git:
  submodules: false
before_install:
  - git clone https://${TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
before_script:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sed -i 's/--abort-on-container-exit/-d/' bin/first-build.sh
  - cd fetch
  - git checkout develop
  - TAB=$'\t'
  - sed -i '/-c 5/ a \'"${TAB}"'\ until curl --silent -XGET --fail http://elasticsearch:9200; do printf \'.'\; sleep 1; done' Makefile
  - cd -
script:
  - ./bin/first-build.sh
  - docker ps --format '{{.Image}}' | sort >> docker_up_output.txt
  - DIFF=$(diff docker_up_output.txt test/image_names.txt)
  - if [ "${DIFF}" != "" ];  then exit 1; fi;
notifications:
  slack:
    rooms:
      secure: kYmigABNJVb+oYYk46yrI0XLM+tlPTHXRgUk1zxh4XsJYUL03YOoj3ywgxMg3q52EAAFzaZ8vFOQSCITtLbGb5HIm7AJ2kTlz5JED1bIUOjy93g9xSQuimCsU+BYrtnEk3sq+ouyrlD42Yy1O5v+qQTwhvBxkDW+1Y22ed7z40aD2iN4W8+ICxzTlic/bFAIYsMgW/9QHIZEjtgHVHncYj6zYogGYS6frorMpQv8Js5gzmaZJHelMybnFTGXOKSU6Qv3Lar7rjzjY8O+uAca9DWcLMqSBE9AHfkcMD8Px1cJe/nG62lzt1pYO+oN3Q0WuFQg85m1GGVTUTkwhV2YgTOjKH6uTrrL4LYcsrKreRL6e+/Own9quKcNQwmodLJ68lZOHF7nKUEA+gpPGj21W4tkm+urKzJglhoIGRhU5hT9jw41anav1n47K4qeda8b4IJrE6/hWKUlfnaAuXTnq59V2Gx4VvfUKPgOkod/1VvzdJEfxOgVgANNxp5dPMg+4yTHCooxeL48p23uf2bNY58JlQftVoYUKzT2zwhorq1bqmVvMlBhx+6h1OJegm0GyxBUcafTvRyBaAAhILXGF5kqP8lhurc72+yg9DbSP+YQx+5jIJm5GjrD95833mqmJZUDzMhj2SG/eyfFx/sfRub+V8q39yIyCJXNG1v/ruU=
