dist: bionic
language: bash
services:
  - docker
before_script:
- git clone https://${TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
- d=configurator/check/travis/alegre/; for f in $(find $d -type f); do cp "$f" "pender/${f/$d/}"; done
- d=configurator/check/travis/check-api/; for f in $(find $d -type f); do cp "$f" "pender/${f/$d/}"; done
script:
  - bin/git-update.sh
  - docker-compose up -d
  - sleep 180
  - docker ps --format '{{.Image}}' | sort >> docker_up_output.txt
  - DIFF=$(diff docker_up_output.txt image_names.txt) 
  - if [ "$DIFF" != "" ] ;  then
       exit 1
    fi