dist: bionic
services:
- postgresql
git:
  submodules: false
before_install:
  - git clone https://${TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
before_script:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sleep 10
script:
  - ./bin/first-build.sh
  - docker-compose up -d
  - docker ps --format '{{.Image}}' | sort >> docker_up_output.txt
  - DIFF=$(diff docker_up_output.txt image_names.txt) 
  - if [ "${DIFF}" != "" ];  then
      exit 1;
    fi;