dist: bionic
services:
  - docker
git:
  submodules: false
before_install:
  - git clone https://${TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
before_script:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
script:
  - git submodule update --init --recursive
  - ./bin/first-build.sh
  - docker-compose up -d
  - docker ps --format '{{.Image}}' | sort
  - docker ps --format '{{.Image}}' | sort >> docker_up_output.txt
  - cat docker_up_output.txt
  - cat image_names.txt
  - DIFF=$(diff docker_up_output.txt image_names.txt) 
  - if [ "${DIFF}" != "" ];  then
      exit 1
    fi