dist: bionic
services:
  - docker
git:
  submodules: false
before_install:
  # - git clone https://${TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
before_script:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
script:
  - cat .gitmodules
  - bin/git-update.sh
  - docker-compose up -d
  - sleep 60
  - docker ps --format '{{.Image}}' | sort
# - docker ps --format '{{.Image}}' | sort >> docker_up_output.txt
#   - DIFF=$(diff docker_up_output.txt image_names.txt) 
#   - if [ "$DIFF" != "" ] ;  then
#        exit 1
#     fi