version: "2.1"
services:
  chromedriver:
    build: chromedriver
    ports:
      - 5900:5900
    environment:
      no_proxy: localhost
      HUB_ENV_no_proxy: localhost
    volumes:
      - "./check-web/test/spec/test.png:/app/test/spec/test.png"
  api:
    environment:
      RAILS_ENV: test
      SERVER_PORT: 3000
  api-background:
    environment:
      RAILS_ENV: test
      SERVER_PORT: 3000
  pender:
    environment:
      RAILS_ENV: test
      SERVER_PORT: 3200
  pender-background:
    environment:
      RAILS_ENV: test
      SERVER_PORT: 3200
  web:
    depends_on:
      - api
      - chromedriver
    environment:
      PLATFORM: web
      NODE_ENV: development
      SERVER_PORT: 3333
      MODE: test
  alegre:
    environment:
      BOILERPLATE_ENV: test
      ALEGRE_PORT: 3100
      REDIS_DATABASE: 3
  vframe:
    environment:
      DB_NAME: vframe_test
      FLASK_ENV: test
  montage:
    depends_on:
      - api
      - chromedriver
